### ISSUE TITLE
Planet image sizes are inconsistent.

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#233]
The starmap shows planets of size 100 as the biggest with sizes 80 and 120 as the same image size (but smaller than planet size 100).

I suspect this may have happened because of some early idea that planets would only go up to size 100, not 121.

This calculation is done in numerous places.

var pSize = ((100 - Math.abs(this.data.size - 100)) / (100 / this.tileSizeInPx)) + 15;

**Comment by 1vasari** [comment]
For similar reasons to #281 I am going to leave this until I get round to straightening this mess in the new UI efforts.

**Comment by 1vasari** [comment]
This issue is now being tracked at https://github.com/plainblack/Lacuna-Web-Client/issues/109
