### ISSUE TITLE
Web-client SS Lab

### ISSUE THREAD

**Issue by Jazzeroki** [plainblack/Lacuna-Server-Open#25]
SS Lab won't let you build a new plan after rushing the current building one without closing and re-opening the window.

**Comment by 1vasari** [comment]
For similar reasons to #281 I am going to leave this until I get round to straightening this mess in the new UI efforts.

Also, most people use scripts to do this anyway. Most certainly there have been few complaints about this issue. :grinning:

**Comment by 1vasari** [comment]
This issue is now being tracked at https://github.com/plainblack/Lacuna-Web-Client/issues/108
