### ISSUE TITLE
Web Client Shipyard available docks counter

### ISSUE THREAD

**Issue by Jazzeroki** [plainblack/Lacuna-Server-Open#26]
When batch building ships the available docks counter only decreases by 1 no matter how many ships are built.

**Comment by 1vasari** [comment]
This bug has evolved a little. :hamburger: 

What happens right now is that when you build a ship the docks available and queue space counters don't update at all.

**Comment by 1vasari** [comment]
As far as I can tell, this one got fixed somewhere. Can we close this?
