### ISSUE TITLE
Supply Pod timeout shown on PCC 'working'.

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#298]
Put the timer for the next supply pod as a 'working' timer on the PCC.

We could then add a 'subsidize work' button (for 2E) to be able to send another pod sooner.

**Comment by 1vasari** [comment]
Is there an API call implemented for this?

**Comment by dmcbride** [comment]
Yup, it's been there for a while, we just haven't put the button in.

http://us1.lacunaexpanse.com/api/PlanetaryCommand.html#subsidize_pod_cooldown_(_session_id%2C_building_id_)

**Comment by 1vasari** [comment]
This issue is now being tracked at https://github.com/plainblack/Lacuna-Web-Client/issues/111
