### ISSUE TITLE
Player notes per-planet

### ISSUE THREAD

**Issue by dmcbride** [plainblack/Lacuna-Server-Open#331]
This is for populated planets only (not for asteroids or planets you may be mining or excavating).

Basically, a new column for bodies (planets, gas giants, stations), visible in the PCC/SCC, for players to put notes.  In stations, alliances can leave notes for their allies.

Need both abandoning and colonising to clean this out, on colonising to ensure it's cleaned up so it doesn't leak through.

Also, flipping a planet should clear this field.

AIs can use it for temporary data as well (a json field or something).

**Comment by Imzogelmo** [comment]
I like it!

**Comment by The-Collective** [comment]
![image](https://cloud.githubusercontent.com/assets/8398804/6654246/24d1b51e-ca85-11e4-9fc0-2b2d43fa126e.png)

**Comment by dmcbride** [comment]
Unscrupulous links? I'm not seeing that as a problem here if only because it's you and, if it's a station, your allies, who can see it.  If the planet is flipped, the notes get junked, so you can't even troll someone who is about to take your planet from you.

That said, similar levels of filtering as email may be somewhat prudent if only to simplify the UI.
