### ISSUE TITLE
Players can have more than 2 planets in starter zone

### ISSUE THREAD

**Issue by Imzogelmo** [plainblack/Lacuna-Server-Open#343]
I'm not sure how it's happening, although I have a suspicion and will just have to locate the code that handles this, but I can confirm it does happen.

**Comment by lemming552** [comment]
It's very easy.  All they have to do is flip a planet.   Last time I looked, none of the players were active.

**Comment by dmcbride** [comment]
Rhu, just going off the top of my head, but there will be code to figure out what missions a spy can perform, as well as code to figure out that a spy can perform the action just requested (I think they share a common list).  That list would need to be generated such that if the target is in the SZ, and the attacker already has two or more colonies in the SZ, insurrection isn't included.  And figuring out the SZ stuff should already be done in code handling the colony ships.  (It's also in the BHG code, but I suspect the colony ship code might be easier to locate and read.)

**Comment by Imzogelmo** [comment]
I looked and could not find where in_starter_zone is defined, but I suspect that would be a good start.

**Comment by The-Collective** [comment]
I do recall a player not being able to flip a planet in SZ since he already had 2 there

**Comment by lemming552** [comment]
That player was wrong.  There's no check for starter zone in Spies.pm nor has there ever been.

It's not a huge deal.  Same four empires that have more than 2, are the same empires from my last check.  If anything is done to stop this, it will probably be more like you can't gain happiness on planets in starter zones if you have more than two.

**Comment by Imzogelmo** [comment]
It's not a terribly big deal to me, but I can fathom ways in which it could be abused (a full ROF vs. the 2-max planets trying to counter them?) . Plus I don't relish the  thought of telling some newbie that they can't have more than 2 planets in the SZ when they retort with "nuh-uh, my neighbor has 3 right here!"

**Comment by lemming552** [comment]
I'm thinking something that if you have over 2 planets in the starter zones:
A) You'll get a warning email.  (Perhaps nightly?)
B) None of the starter zone planets will be able to gain happiness. (Possibly a slow degrade)

That allows someone to still attack someone in the starter zone even if they have a couple planets, but makes sure they don't leave extras there.

**Comment by Imzogelmo** [comment]
Option B) seems rather harsh, don't you think?

**Comment by lemming552** [comment]
Not really.  They'll get an immediate notice about it and can do something about it.  If they're intending just to do a flip and abandon, there's a minimum of disruption.  Or even if they then move out.
The other option is to make planets immune against people with 2 planets in the starter zones.
And a simple warning hasn't worked.

**Comment by Imzogelmo** [comment]
I suppose you're right, but a lot of the empires in this situation are barely active, and decreasing happiness would only hasten their... demise.

**Comment by lemming552** [comment]
Code for this has now been in place for months where starter zone planets do not gain happiness if there are more than two.
