### ISSUE TITLE
60 day max travel time

### ISSUE THREAD

**Issue by ghotier** [plainblack/Lacuna-Server-Open#350]
From the update 3.0909  - Mod: Minimum flight time: 5 Minutes, Maximum is 2 months.

This does not seem to be working correctly (minor bug).

I was just sending a surveyor to a planet pretty far out from me (6.5 hours for the surveyor). In the list of possible ships to send was a Space Station Hull. It listed a travel time of 71+ days.

I did not actually send the space station hull, so I do not know if it was showing 71 days but would actually take 60 days if sent (in any case the time shown for transit should match the actual time), or if it would take 71 days and change to get there (which then means the update max travel time is off).

If the max travel time is 60 days, that would mean that you should just set the travel time to any destination to 60 days OR if you should not show the SS Hull as a valid ship to send since it can not travel that distance in less then 60 days.....

Hope this makes sense.

**Comment by lemming552** [comment]
A future enhancement of the UI will disable the send button on ships that can not be sent.
Either ones that could not arrive by a set arrival time or ones that will take over 60 days.

Not a server bug, it's a client bug.  If you had pressed send, it would have told you that was not a possible trip.

**Comment by lemming552** [comment]
Since we can't track well in the web client, leaving this here.

**Comment by 1vasari** [comment]
This issue is now being tracked at https://github.com/plainblack/Lacuna-Web-Client/issues/112
