### ISSUE TITLE
Option for shipyards to automatically spread out ship building over multiple yards

### ISSUE THREAD

**Issue by dmcbride** [plainblack/Lacuna-Server-Open#351]
commit 5bc231cb added a top number of adding to the queue of 600, so maybe an option to get the server to automatically spread this out over all the yards (of the same level - or higher?), again, to save RPCs.

**Comment by Imzogelmo** [comment]
So basically a 'normalize' routine for ship build queues?

**Comment by dmcbride** [comment]
Something like that.  And if we can get it in the UI as some sort of option, that allows even non-scripters to be able to build lots of ships efficiently without a boatload of clicking.

**Comment by Imzogelmo** [comment]
Seems reasonable. You could have it sort all shipyards in descending order, then fill them to their (individual) max queues as it goes down the list, till the order is done or you reach 600, whichever comes first... That should be the default, I would say, but it should also be possible to *not* do it, as you may want to build different kinds of ships in parallel.

**Comment by 1vasari** [comment]
:+1: for option to not try to spread over all shipyards.

**Comment by dmcbride** [comment]
If you have some shipyards at a lower level, those ships won't be as fast/strong/big as the ones built at higher level SYs.  If they're all at 30, no problem, but if you have some higher and some lower, then you may want to restrict to the higher ones.  So having a way to specify "this SY only" (the current method) vs "all SYs at highest level" vs "all SYs at this level or higher" vs "all SYs, period" would be nice.

The goal isn't to handle every scenario, of course, the goal is just to make the common scenarios easier.

@1vasari - you coming back to help again? :)

**Comment by 1vasari** [comment]
@dmcbride I've been lurking. ;)

**Comment by Imzogelmo** [comment]
Yes. Common scenarios: 
1. Build all at one. Either don't care about time or saving other yards for different builds...
2. Optimize for time. Maybe you are building sweepers and snark3s, so you spread your snark3s out more than your sweepers. Obviously simply spreading out the order won't help there, you'd have to have a sort of pre-order system to get the whole order together before sending it.
3. Build only max ships. -> Leave the ones less than 30 at idle. We can already do this, pretty much, if you have any level 30s....

With the way it is now (50 max queue) you can have a 30 and a 20, and queue 50 at the 30. Under the change, you could have 10 30s and 15 20s and queue the whole 600 at the 10 30s (60 each ideally) or if you don't care about time and only care about fewest RPCs, you can do the 600 on a single yard.

**Comment by dmcbride** [comment]
API options as I've got them right now (subject to change as I continue working on it):

1. `body_id` or `building_id` - Don't need both.  Also, building_id can be a list of building IDs, thus allowing the caller to specify which SYs to use (this can come in handy in the new UI, Vas).  Select these three to make snarks, and those two to make sweepers? No problem.  Still two calls, though.

2. `autoselect`
  - `all` will use the body_id from above (derived from the building_id if body_id not given, which may or may not make the caller code easier), and simply select all SYs.  Not more than one `building_id` should be specified.
  - `higher` will select all SYs at a level equal to or higher than the selected SY.  Only one `building_id` can be specified as a comparison.
  - `only` will select all SYs at the exact same level as the selected SY.  Only one `building_id` can be specified as a comparison.
  - Not set will only select the building_id(s) provided.  So far, this is the only way that passing in multiple `building_id`s make any sense.

Regardless of the above, the action will always be to try to spread out the builds to optimise for time.  Of course, if only one SY is selected, there's not much to optimise.  This optimisation can play into any of the above scenarios especially if some SYs already are building stuff.  For example, start building sweepers in some SYs, and then build snarks in *all* SYs, and the SYs building sweepers won't be tasked with snarks until all the rest of the SYs are busy for just as long.
