### ISSUE TITLE
Bleeders do not deploy to row y=-6

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#379]
I sent 20 bleeders from 'chilly' to 'chilly'. When they arrived (after 5 minutes) nine of them deployed to free spaces in the -5 to +5 map ranges.

No bleeders deployed to the y=-6 row

**Comment by dmcbride** [comment]
Nothing deploys to the y=-6 row.  It was a [bad hack](https://github.com/plainblack/Lacuna-Web-Client/commit/437bf9a7b8069236786bfaa81825a37ba6d2067d) to try to let users move their planet around such that they can see the full bottom row (y=-5).  It was [fixed properly in master](https://github.com/plainblack/Lacuna-Web-Client/commit/be74df7a0c38b322ef89ddc2812cd07fe8697442] by removing the y=-6 row and providing proper outer buffer space.  I thought the bad hack was still better than not being able to see that bottom row (as it was receiving a lot of complaints), but kept working on a better fix until I finally found the right place to tweak.

Bleeders, pods, etc. will eventually deploy to x=6 (on the right), as I understand it.
