### ISSUE TITLE
Tweak to shipyard queue size

### ISSUE THREAD

**Issue by xHusky** [plainblack/Lacuna-Server-Open#384]
My proposal is to equalize the shipyard queue size with the number of available docks.

To understand the necessity of this change, imagine a case where you have 3000 available docks and one level 30 shipyard. Currently you would have to create 100 queues to fill that space up which is already tedious enough and wastes a lot of time due to the discontinuity between the queues. And what difference does it make for the game if you queue 100x30 ships or 1x3000 ships?

This would be a huge help for newer empires, and building multiple shipyards would still make sense to have parallel queues.

**Comment by lemming552** [comment]
Currently, it does matter because the client has to wait for the returned status.  And having it limited by # of shipyard levels makes sense anyway.
