### ISSUE TITLE
automated tests for lacuana JSON/RPC api using swat

### ISSUE THREAD

**Issue by melezhik** [plainblack/Lacuna-Server-Open#391]
Hi I dropped [some tests](https://github.com/melezhik/swat-lacuna-api) using [swat](https://github.com/melezhik/swat) for lacuna JSON/RCP, it includes:
- uploading servers.json
- successful login (empire/login method) and check if session_id present with fuhrer caching of session_id to minimize repetitious logins  
- successful profile view ( empire/view_profile method ) and check if a proper empire name present 
- successful   stats/credits method call and check some output here

---

https://github.com/melezhik/swat-lacuna-api

This is only a simple example,  if guys this sounds interesting for you we could discuss a possible co-working for swat and lacuna api, Possible directions:
- automated health , smoke checks with swat for lacuna services  monitoring 
- automated functional tests with swat for developers 

Thanks ahead of time for your feedback.

Alexey

**Comment by icydee** [comment]
This looks very exciting, thanks for pointing out swat to us I can see lots of uses for it.

Although I personally don't develop for TLE anymore I can see uses for swat in my $work. I will have to investigate further!

(There are others still developing TLE so they can comment on it's use there...)

**Comment by melezhik** [comment]
Sure, Iain . If you need more information on it - you may ask me.
If you know someone related to http://us1.lacunaexpanse.com/api please forward this for them.
