### ISSUE TITLE
Service life for a probe before natural degradation

### ISSUE THREAD

**Issue by RedOrion** [plainblack/Lacuna-Server-Open#401]
Say the probe slowly gets piled into the stars corona

**Comment by 1vasari** [comment]
Nobody really uses probes anymore, this kinda thing would just make them less desirable, IMO.

**Comment by dmcbride** [comment]
On one hand, there's a certain amount of verisimilitude that something like this would bring.  But then we have to weigh the benefit of that verisimilitude against the annoyance and the code.

The code required to run and find stale probes and email their owners with "the probe in the _XYZ_ system went dark after running out of fuel" emails, and all that.  Versus gameplay and balance.

Unlike exploding excavs, I don't see this bringing balance, only annoyance to the players.  And, while it does make a certain amount of sense, I'm not seeing a benefit to the game overall.

Truly stale probes get removed from the database when the player goes inactive and destructs.  If inactive players aren't destructing often enough, sitter access will hopefully go a long way to that end, and is probably a better tactic for cleaning up stale probes.

So I'm voting to leave abandon (pun intended) this issue.

**Comment by 1vasari** [comment]
@dmcbride :+1:
