### ISSUE TITLE
Remove Escavator deployed messages.

### ISSUE THREAD

**Issue by Watowi** [plainblack/Lacuna-Server-Open#404]
Understand ths was once useful. However it no longer serves a purpose.
Less spam is better.

**Comment by lemming552** [comment]
"Stop Excavator Replace Alert"  option can be checked if you do not want the email.

**Comment by dmcbride** [comment]
I wonder if a better description in the UI for this would be warranted, because I didn't know that's what that checkbox did.

**Comment by dmcbride** [comment]
That option does two things, I think.  It stops the excav emails from telling you how many excavs you have left AND stops the excav deployed email.

**Comment by Watowi** [comment]
Copies of the 2 current excavator messages:

Excavator results:
The Archeology Ministry of Charlie5 has received the following results from its excavator sites.

Regards,

Your Humble Assistant
SiteTypeResultIom Blique Yu 2DestroyedDave, this conversation can serve no purpose anymore. Goodbye.Iom Blique Yu 2ReplaceSuccess : Excavator launched. 22 left.








"
has all the information necessary to manage excavators.

While the deployed msg:
The Excavator from Charlie5 has deployed on Iom Blique Yu 2.
It is now operational and will start sending back its results.

Regards,

Excavator Commander"
Is currently nothing but fluff/spam.
Thank you for looing into this.


Date: Tue, 29 Dec 2015 16:49:04 -0800

**Comment by Watowi** [comment]
Does that stop "deployed", "results", or both?
The "results" message is useful as it provides the total remaining excavators on a colony.
Perhaps only refining the description of what an alert is would solve the issue?
Date: Tue, 29 Dec 2015 13:23:39 -0800

**Comment by lemming552** [comment]
I wouldn't remove the message, just because someone considers it fluff.  Info that it either deployed or got destroyed to some might be useful.  (I think most people just turn off most excav messages)
If anything, having two different options to turn off either would be best, which brings up the plan of redoing how mail is handled.  Currently, a bunch of switches in the empire table seems to me to be clunky, while a filter of some sort would be better.  Which is outside the scope of this issue.

**Comment by Watowi** [comment]
Turning off all excavator messages makes me wonder how they handle excavarot populations.

Results:
Iom Blique Yu 2DestroyedDave, this conversation can serve no purpose anymore. Goodbye.Iom Blique Yu 2ReplaceSuccess : Excavator launched. 22 left.
Deployed:
The Excavator from Charlie5 has deployed on Iom Blique Yu 2.
It is now operational and will start sending back its results.

As you can see the information in the Deployed message is also in the Rseults message, making the Deployed message redundant.
Date: Wed, 30 Dec 2015 09:05:09 -0800
