### ISSUE TITLE
BHG firing on planets in seized star systems

### ISSUE THREAD

**Issue by icydee** [plainblack/Lacuna-Server-Open#93]
systems are often seized in order to ensure mining, excavator and colonisation rights to the planets in that system.

however a BHG is able to convert the types of those planets, or turn them into asteroids, thus destroying those rights.

Although it would not be appropriate to prevent BHG from doing this, there should at least be an email informing the (whole?) alliance which BHG was responsible for the aggressive act so that they can carry out an appropriate response.

**Comment by lemming552** [comment]
Closing since we now have some ways around this.
